export const SAVE_VIDEO = "SAVE_VIDEO";
export const SAVE_VIDEO_SUCCESSFUL = "SAVE_VIDEO_SUCCESSFUL";
export const SAVE_VIDEO_FAILED = "SAVE_VIDEO_FAILED";

export const DELETE_VIDEO = "DELETE_VIDEO";
export const DELETE_VIDEO_SUCCESSFUL = "DELETE_VIDEO_SUCCESSFUL";
export const DELETE_VIDEO_FAILED = "DELETE_VIDEO_FAILED";

export const RESET_SAVE_VIDEO_FLAG = "RESET_SAVE_VIDEO_FLAG";
