export const GALLERY_LIST = "GALLERY_LIST";
export const GALLERY_LIST_SUCCESSFUL = "GALLERY_LIST_SUCCESSFUL";
export const GALLERY_LIST_FAILED = "GALLERY_LIST_FAILED";
export const RESET_GALLERY_LIST_FLAG = "RESET_GALLERY_LIST_FLAG";
export const REFRESH_GALLERY_LIST_FLAG = "REFRESH_GALLERY_LIST_FLAG";
