export const VIDEO_LIST = "VIDEO_LIST";
export const VIDEO_LIST_SUCCESSFUL = "VIDEO_LIST_SUCCESSFUL";
export const VIDEO_LIST_FAILED = "VIDEO_LIST_FAILED";
export const RESET_VIDEO_LIST_FLAG = "RESET_VIDEO_LIST_FLAG";
export const REFRESH_VIDEO_LIST_FLAG = "REFRESH_VIDEO_LIST_FLAG";
