export const PORTFOLIO_LIST = "PORTFOLIO_LIST";
export const PORTFOLIO_LIST_SUCCESSFUL = "PORTFOLIO_LIST_SUCCESSFUL";
export const PORTFOLIO_LIST_FAILED = "PORTFOLIO_LIST_FAILED";
export const RESET_PORTFOLIO_LIST_FLAG = "RESET_PORTFOLIO_LIST_FLAG";
export const REFRESH_PORTFOLIO_LIST_FLAG = "REFRESH_PORTFOLIO_LIST_FLAG";
