export const WITHDRAW_LIST = "WITHDRAW_LIST";
export const WITHDRAW_LIST_SUCCESSFUL = "WITHDRAW_LIST_SUCCESSFUL";
export const WITHDRAW_LIST_FAILED = "WITHDRAW_LIST_FAILED";
export const RESET_WITHDRAW_LIST_FLAG = "RESET_WITHDRAW_LIST_FLAG";
export const REFRESH_WITHDRAW_LIST_FLAG = "REFRESH_WITHDRAW_LIST_FLAG";
