export const DONOR_LIST = "DONOR_LIST";
export const DONOR_LIST_SUCCESSFUL = "DONOR_LIST_SUCCESSFUL";
export const DONOR_LIST_FAILED = "DONOR_LIST_FAILED";
export const RESET_DONOR_LIST_FLAG = "RESET_DONOR_LIST_FLAG";
export const REFRESH_DONOR_LIST_FLAG = "REFRESH_DONOR_LIST_FLAG";
