export const PORTFOLIO_SHOW_DETAIL = "PORTFOLIO_SHOW_DETAIL";
export const PORTFOLIO_SHOW_DETAIL_SUCCESSFUL = "PORTFOLIO_SHOW_DETAIL_SUCCESSFUL";
export const PORTFOLIO_SHOW_DETAIL_FAILED = "PORTFOLIO_SHOW_DETAIL_FAILED";
export const RESET_PORTFOLIO_SHOW_DETAIL_FLAG = "RESET_PORTFOLIO_SHOW_DETAIL_FLAG";
