export const CAMPAIGN_SHOW_DETAIL = "CAMPAIGN_SHOW_DETAIL";
export const CAMPAIGN_SHOW_DETAIL_SUCCESSFUL = "CAMPAIGN_SHOW_DETAIL_SUCCESSFUL";
export const CAMPAIGN_SHOW_DETAIL_FAILED = "CAMPAIGN_SHOW_DETAIL_FAILED";
export const RESET_CAMPAIGN_SHOW_DETAIL_FLAG = "RESET_CAMPAIGN_SHOW_DETAIL_FLAG";
