export const CAMPAIGN_LIST = "CAMPAIGN_LIST";
export const CAMPAIGN_LIST_SUCCESSFUL = "CAMPAIGN_LIST_SUCCESSFUL";
export const CAMPAIGN_LIST_FAILED = "CAMPAIGN_LIST_FAILED";
export const RESET_CAMPAIGN_LIST_FLAG = "RESET_CAMPAIGN_LIST_FLAG";
export const REFRESH_CAMPAIGN_LIST_FLAG = "REFRESH_CAMPAIGN_LIST_FLAG";
