export const SAVE_CAMPAIGN = "SAVE_CAMPAIGN";
export const SAVE_CAMPAIGN_SUCCESSFUL = "SAVE_CAMPAIGN_SUCCESSFUL";
export const SAVE_CAMPAIGN_FAILED = "SAVE_CAMPAIGN_FAILED";

export const DELETE_CAMPAIGN = "DELETE_CAMPAIGN";
export const DELETE_CAMPAIGN_SUCCESSFUL = "DELETE_CAMPAIGN_SUCCESSFUL";
export const DELETE_CAMPAIGN_FAILED = "DELETE_CAMPAIGN_FAILED";

export const RESET_SAVE_CAMPAIGN_FLAG = "RESET_SAVE_CAMPAIGN_FLAG";
