export const MEMBER_SHOW_DETAIL = "MEMBER_SHOW_DETAIL";
export const MEMBER_SHOW_DETAIL_SUCCESSFUL = "MEMBER_SHOW_DETAIL_SUCCESSFUL";
export const MEMBER_SHOW_DETAIL_FAILED = "MEMBER_SHOW_DETAIL_FAILED";
export const RESET_MEMBER_SHOW_DETAIL_FLAG = "RESET_MEMBER_SHOW_DETAIL_FLAG";
