export const SAVE_WITHDRAW = "SAVE_WITHDRAW";
export const SAVE_WITHDRAW_SUCCESSFUL = "SAVE_WITHDRAW_SUCCESSFUL";
export const SAVE_WITHDRAW_FAILED = "SAVE_WITHDRAW_FAILED";

export const DELETE_WITHDRAW = "DELETE_WITHDRAW";
export const DELETE_WITHDRAW_SUCCESSFUL = "DELETE_WITHDRAW_SUCCESSFUL";
export const DELETE_WITHDRAW_FAILED = "DELETE_WITHDRAW_FAILED";

export const RESET_SAVE_WITHDRAW_FLAG = "RESET_SAVE_WITHDRAW_FLAG";
