export const WITHDRAW_SHOW_DETAIL = "WITHDRAW_SHOW_DETAIL";
export const WITHDRAW_SHOW_DETAIL_SUCCESSFUL = "WITHDRAW_SHOW_DETAIL_SUCCESSFUL";
export const WITHDRAW_SHOW_DETAIL_FAILED = "WITHDRAW_SHOW_DETAIL_FAILED";
export const RESET_WITHDRAW_SHOW_DETAIL_FLAG = "RESET_WITHDRAW_SHOW_DETAIL_FLAG";
