export const GALLERY_SHOW_DETAIL = "GALLERY_SHOW_DETAIL";
export const GALLERY_SHOW_DETAIL_SUCCESSFUL = "GALLERY_SHOW_DETAIL_SUCCESSFUL";
export const GALLERY_SHOW_DETAIL_FAILED = "GALLERY_SHOW_DETAIL_FAILED";
export const RESET_GALLERY_SHOW_DETAIL_FLAG = "RESET_GALLERY_SHOW_DETAIL_FLAG";
