export const SAVE_PORTFOLIO = "SAVE_PORTFOLIO";
export const SAVE_PORTFOLIO_SUCCESSFUL = "SAVE_PORTFOLIO_SUCCESSFUL";
export const SAVE_PORTFOLIO_FAILED = "SAVE_PORTFOLIO_FAILED";

export const DELETE_PORTFOLIO = "DELETE_PORTFOLIO";
export const DELETE_PORTFOLIO_SUCCESSFUL = "DELETE_PORTFOLIO_SUCCESSFUL";
export const DELETE_PORTFOLIO_FAILED = "DELETE_PORTFOLIO_FAILED";

export const RESET_SAVE_PORTFOLIO_FLAG = "RESET_SAVE_PORTFOLIO_FLAG";
