export const CREATE_MEMBER = "CREATE_MEMBER";
export const CREATE_MEMBER_SUCCESSFUL = "CREATE_MEMBER_SUCCESSFUL";
export const CREATE_MEMBER_FAILED = "CREATE_MEMBER_FAILED";

export const DELETE_MEMBER = "DELETE_MEMBER";
export const DELETE_MEMBER_SUCCESSFUL = "DELETE_MEMBER_SUCCESSFUL";
export const DELETE_MEMBER_FAILED = "DELETE_MEMBER_FAILED";

export const RESET_CREATE_MEMBER_FLAG = "RESET_CREATE_MEMBER_FLAG";
