export const MEMBER_LIST = "MEMBER_LIST";
export const MEMBER_LIST_SUCCESSFUL = "MEMBER_LIST_SUCCESSFUL";
export const MEMBER_LIST_FAILED = "MEMBER_LIST_FAILED";
export const RESET_MEMBER_LIST_FLAG = "RESET_MEMBER_LIST_FLAG";
export const REFRESH_MEMBER_LIST_FLAG = "REFRESH_MEMBER_LIST_FLAG";
