export const DASHBOARD_SHOW_DETAIL = "DASHBOARD_SHOW_DETAIL";
export const DASHBOARD_SHOW_DETAIL_SUCCESSFUL = "DASHBOARD_SHOW_DETAIL_SUCCESSFUL";
export const DASHBOARD_SHOW_DETAIL_FAILED = "DASHBOARD_SHOW_DETAIL_FAILED";
export const RESET_DASHBOARD_SHOW_DETAIL_FLAG = "RESET_DASHBOARD_SHOW_DETAIL_FLAG";
