export const MEMBERINFORMATION_SHOW_DETAIL = "MEMBERINFORMATION_SHOW_DETAIL";
export const MEMBERINFORMATION_SHOW_DETAIL_SUCCESSFUL = "MEMBERINFORMATION_SHOW_DETAIL_SUCCESSFUL";
export const MEMBERINFORMATION_SHOW_DETAIL_FAILED = "MEMBERINFORMATION_SHOW_DETAIL_FAILED";
export const RESET_MEMBERINFORMATION_SHOW_DETAIL_FLAG = "RESET_MEMBERINFORMATION_SHOW_DETAIL_FLAG";
