export const VIDEO_SHOW_DETAIL = "VIDEO_SHOW_DETAIL";
export const VIDEO_SHOW_DETAIL_SUCCESSFUL = "VIDEO_SHOW_DETAIL_SUCCESSFUL";
export const VIDEO_SHOW_DETAIL_FAILED = "VIDEO_SHOW_DETAIL_FAILED";
export const RESET_VIDEO_SHOW_DETAIL_FLAG = "RESET_VIDEO_SHOW_DETAIL_FLAG";
