export const CREATE_MEMBERINFORMATION = "CREATE_MEMBERINFORMATION";
export const CREATE_MEMBERINFORMATION_SUCCESSFUL = "CREATE_MEMBERINFORMATION_SUCCESSFUL";
export const CREATE_MEMBERINFORMATION_FAILED = "CREATE_MEMBERINFORMATION_FAILED";

export const DELETE_MEMBERINFORMATION = "DELETE_MEMBERINFORMATION";
export const DELETE_MEMBERINFORMATION_SUCCESSFUL = "DELETE_MEMBERINFORMATION_SUCCESSFUL";
export const DELETE_MEMBERINFORMATION_FAILED = "DELETE_MEMBERINFORMATION_FAILED";

export const RESET_CREATE_MEMBERINFORMATION_FLAG = "RESET_CREATE_MEMBERINFORMATION_FLAG";
