export const SAVE_GALLERY = "SAVE_GALLERY";
export const SAVE_GALLERY_SUCCESSFUL = "SAVE_GALLERY_SUCCESSFUL";
export const SAVE_GALLERY_FAILED = "SAVE_GALLERY_FAILED";

export const DELETE_GALLERY = "DELETE_GALLERY";
export const DELETE_GALLERY_SUCCESSFUL = "DELETE_GALLERY_SUCCESSFUL";
export const DELETE_GALLERY_FAILED = "DELETE_GALLERY_FAILED";

export const RESET_SAVE_GALLERY_FLAG = "RESET_SAVE_GALLERY_FLAG";
